"""
SysSight - Network Service Module
Executes 'ss -tulnp' through command_runner to inspect active listening network sockets,
ports, and associated processes, packaging results into a standardized payload.
"""

import os
import re
import sys

# Ensure parent 'backend' directory is in sys.path for both direct execution and package imports
CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
BACKEND_ROOT = os.path.dirname(CURRENT_DIR)
if BACKEND_ROOT not in sys.path:
    sys.path.insert(0, BACKEND_ROOT)

try:
    from backend.command_runner import run_command
except ImportError:
    from command_runner import run_command


def parse_ss(raw_output: str) -> list[dict]:
    """
    Parses table generated by 'ss -tulnp' into structured network socket entries.

    Extracts protocol, local address, listening port, socket state, process PID,
    and process name while defending against varied whitespace and formatting.
    """
    parsed = []
    if not raw_output:
        return parsed

    lines = raw_output.strip().splitlines()
    if not lines:
        return parsed

    for line in lines:
        line_clean = line.strip()
        if not line_clean:
            continue

        # Skip header line(s)
        if line_clean.startswith("Netid") or "Local Address:Port" in line_clean:
            continue

        # Split into columns: Netid, State, Recv-Q, Send-Q, Local Address:Port, Peer Address:Port, [Process]
        parts = line_clean.split(None, 6)
        if len(parts) < 6:
            continue

        protocol = parts[0].strip().lower()
        state = parts[1].strip()
        recv_q = parts[2].strip()
        send_q = parts[3].strip()
        local_addr_port = parts[4].strip()
        peer_addr_port = parts[5].strip()
        process_col = parts[6].strip() if len(parts) > 6 else ""

        # Parse Local Address and Port
        if ":" in local_addr_port:
            local_address, port_str = local_addr_port.rsplit(":", 1)
        else:
            local_address = local_addr_port
            port_str = ""

        try:
            port = int(port_str) if port_str.isdigit() else port_str
        except (ValueError, TypeError):
            port = port_str

        # Parse process name and PID from process column
        # Typical format: users:(("python",pid=1234,fd=3)) or users:(("node",pid=912,fd=18),("node",pid=913,fd=18))
        pid = None
        process_name = "—"
        if process_col:
            user_matches = re.findall(r'"([^"]+)",pid=(\d+)', process_col)
            if user_matches:
                process_name = user_matches[0][0]
                pid = int(user_matches[0][1])
            else:
                # Fallback pattern without quotes: pid=(\d+)
                pid_match = re.search(r'pid=(\d+)', process_col)
                if pid_match:
                    pid = int(pid_match.group(1))
                name_match = re.search(r'\(\("?([^",\)]+)"?', process_col)
                if name_match:
                    process_name = name_match.group(1)

        parsed.append({
            "protocol": protocol,
            "local_address": local_address,
            "port": port,
            "state": state,
            "pid": pid,
            "process": process_name,
            "recv_q": int(recv_q) if recv_q.isdigit() else recv_q,
            "send_q": int(send_q) if send_q.isdigit() else send_q,
            "peer_address": peer_addr_port,
        })

    return parsed


def get_network_info() -> dict:
    """
    Retrieves active listening sockets and port bindings.

    Attempts non-interactive 'sudo -n ss -tulnp' to safely capture elevated process details.
    If sudo is unavailable, requires a password, or fails, cleanly falls back to 'ss -tulnp'.
    Handles permission or missing command errors gracefully without crashing.
    """
    # 1. Attempt non-interactive sudo execution
    cmd_result = run_command(["sudo", "-n", "ss", "-tulnp"])

    # 2. If sudo failed (e.g. requires password or sudo missing), fall back to standard ss
    if cmd_result.get("exit_code") != 0:
        fallback_result = run_command(["ss", "-tulnp"])
        if fallback_result.get("exit_code") == 0:
            cmd_result = fallback_result
        else:
            # Check if ss is missing altogether
            err_msg = fallback_result.get("error", "")
            if fallback_result.get("exit_code") == 127 or "not found" in err_msg.lower():
                cmd_result = fallback_result
                cmd_result["error"] = "ss command is not available. Install iproute2."
            else:
                # Keep fallback result if it provides partial output, or original error
                if fallback_result.get("raw_output"):
                    cmd_result = fallback_result

    # 3. Parse output if raw_output is available
    parsed_data = []
    raw_output = cmd_result.get("raw_output", "")
    if raw_output:
        parsed_data = parse_ss(raw_output)

    # 4. Standardized SysSight response payload
    return {
        "command": "ss -tulnp",
        "timestamp": cmd_result.get("timestamp", ""),
        "raw_output": raw_output,
        "parsed": parsed_data,
        "error": cmd_result.get("error", ""),
        "exit_code": cmd_result.get("exit_code", 0),
    }


if __name__ == "__main__":
    import json
    data = get_network_info()
    print(f"Command: {data['command']}")
    print(f"Exit code: {data['exit_code']}")
    print(f"Parsed sockets count: {len(data['parsed'])}")
    print(json.dumps(data["parsed"][:3], indent=2))
