"""
SysSight - Tracing Service Module
Executes 'strace -c ls' through command_runner to intercept Linux kernel system calls,
captures the profiling summary from stderr, and packages the result into a standardized payload.
"""

import os
import sys

# Ensure parent 'backend' directory is in sys.path for both direct execution and package imports
CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
BACKEND_ROOT = os.path.dirname(CURRENT_DIR)
if BACKEND_ROOT not in sys.path:
    sys.path.insert(0, BACKEND_ROOT)

try:
    from backend.command_runner import run_command
except ImportError:
    from command_runner import run_command


def parse_strace(raw_output: str) -> dict:
    """
    Parses the summary table generated by 'strace -c' into structured metrics.

    Extracts individual syscall metrics (% time, seconds, usecs/call, calls, errors, syscall)
    and aggregate totals for the frontend SyscallCard component.
    """
    syscalls = []
    total_calls = 0
    total_errors = 0
    total_time = 0.0

    if not raw_output:
        return {
            "syscalls": syscalls,
            "total_calls": total_calls,
            "total_errors": total_errors,
            "total_time": total_time,
        }

    for line in raw_output.strip().splitlines():
        line_clean = line.strip()
        if not line_clean or line_clean.startswith("------") or line_clean.startswith("% time"):
            continue

        parts = line_clean.split()
        if not parts:
            continue

        # Check for summary total line: e.g. 100.00 0.004631 31 145 [11] total
        if parts[-1] == "total":
            try:
                total_time = float(parts[1])
                if len(parts) >= 6:
                    total_calls = int(parts[3])
                    total_errors = int(parts[4])
                elif len(parts) == 5:
                    total_calls = int(parts[3])
                    total_errors = 0
            except (ValueError, IndexError):
                pass
            continue

        # Parse syscall line: e.g. 28.11 0.001302 48 27 mmap OR 11.66 0.000540 45 12 1 openat
        try:
            time_pct = float(parts[0])
            seconds = float(parts[1])
            usecs_per_call = int(parts[2])
            if len(parts) >= 6:
                calls = int(parts[3])
                errors = int(parts[4])
                syscall = parts[5]
            else:
                calls = int(parts[3])
                errors = 0
                syscall = parts[4]

            syscalls.append({
                "syscall": syscall,
                "time_pct": time_pct,
                "seconds": seconds,
                "usecs_per_call": usecs_per_call,
                "calls": calls,
                "errors": errors,
            })
        except (ValueError, IndexError):
            continue

    if not total_calls and syscalls:
        total_calls = sum(s["calls"] for s in syscalls)
        total_errors = sum(s["errors"] for s in syscalls)
        total_time = sum(s["seconds"] for s in syscalls)

    return {
        "syscalls": syscalls,
        "total_calls": total_calls,
        "total_errors": total_errors,
        "total_time": total_time,
    }


def get_strace_info() -> dict:
    """
    Retrieves system call profiler metrics for 'ls'.

    Executes live 'strace -c ls' via command_runner. Since strace writes its
    summary table to stderr on Linux, preserves the complete strace output in
    both raw_output and error fields so neither frontend display nor raw stderr is lost.
    """
    cmd_result = run_command(["strace", "-c", "ls"])

    stderr_output = cmd_result.get("error", "")
    stdout_output = cmd_result.get("raw_output", "")

    # 'strace -c' writes the summary table to stderr
    if "% time" in stderr_output:
        raw_summary = stderr_output
    elif "% time" in stdout_output:
        raw_summary = stdout_output
    else:
        raw_summary = stderr_output if stderr_output else stdout_output

    parsed_data = parse_strace(raw_summary)

    return {
        "command": cmd_result.get("command", "strace -c ls"),
        "timestamp": cmd_result.get("timestamp", ""),
        "raw_output": raw_summary,
        "parsed": parsed_data,
        "error": stderr_output,
        "exit_code": cmd_result.get("exit_code", 0),
    }


if __name__ == "__main__":
    import json
    data = get_strace_info()
    print(json.dumps({k: v for k, v in data.items() if k != "raw_output"}, indent=2))
    print(f"raw_output characters: {len(data.get('raw_output', ''))}")
